name: postogram
description: "App for Surf Winter School"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.4
  go_router: 14.2.1
  http: 1.3.0
  intl: 0.19.0
  json_annotation: 4.9.0
  surf_lint_rules: 1.0.0

dev_dependencies:
  analyzer: 5.13.0
  build_runner: 2.4.11
  flutter_lints: 3.0.0
  json_serializable: 6.8.0

flutter:
  uses-material-design: true

  assets:
      - assets/icons/
      - assets/images/
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/roboto.ttf
