name: postogram
description: "App for Surf Winter School"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/icons/
      - assets/images/
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/roboto.ttf
